name: Second Workflow

on:
 issues:
 push:
 workflow_dispatch:


jobs:
 first-job:
  runs-on: ubuntu-latest
  steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v4.5.0
      with:
         distribution: 'microsoft'
         java-version: '17'
         
   
