name: Variables Concepts

on:
 workflow_dispatch:

jobs:
 variables:
   runs-on: ubuntu-latest
   steps: 
    - name: Variables
      run: |
       echo "Value for variable stored ${{vars.MY_VAR}}"
       echo "Secret API Key value to be used ${{secrets.API_KEY}}"
    
